### ISSUE TITLE
no more thermostats after upgrading to 2025.6

### ISSUE THREAD

**Issue by tempod** [h4de5/home-assistant-vimar#93]
after updating to version 2025.6 the thermostats stopped working.
this is the log.

`2025-06-12 19:55:13.985 ERROR (MainThread) [homeassistant.components.climate] Error adding entity None for domain climate with platform vimar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 877, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 314, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar/climate.py", line 122, in supported_features
    flags |= ClimateEntityFeature.AUX_HEAT
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ClimateEntityFeature' has no attribute 'AUX_HEAT'`

![Image](https://github.com/user-attachments/assets/15cf34cc-dad6-433b-a0d1-31c47b3590e2)

the error is the same for all thermostats

**Comment by emanueleaddesi** [comment]
It seems ClimateEntityFeature.AUX_HEAT is no more supported in 2025.6.0.
To fix the problem I've commented line 122 in climate.py file and reboot home assistant.

**Comment by tempod** [comment]
can you post the code?
i tried to modify only line 122 as you suggested but the whole integration stopped working

![Image](https://github.com/user-attachments/assets/d56a3b67-eec6-4b80-ae72-44aea728ac4f)
