### PR TITLE
Remove AUX heating - ready for HA 2025.7

### LINKED ISSUE #93: no more thermostats after upgrading to 2025.6
after updating to version 2025.6 the thermostats stopped working.
this is the log.

`2025-06-12 19:55:13.985 ERROR (MainThread) [homeassistant.components.climate] Error adding entity None for domain climate with platform vimar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 877, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 314, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vimar/climate.py", line 122, in supported_features
    flags |= ClimateEntityFeature.AUX_HEAT
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ClimateEntityFeature' has no attribute 'AUX_HEAT'`

Image

the error is the same for all thermostats

### PR DESCRIPTION
**Pull request by h4de5**
Fixes #93

### CODE REVIEW

**Comment by michemelga** [comment]
great job- You saved me!!!
